import React from 'react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-white border-t border-slate-200 mt-12 py-12">
      <div className="max-w-7xl mx-auto px-4 text-center">
        <p className="text-slate-500">
          Powered by <span className="font-semibold text-slate-800">Gemini 2.5 Flash</span>
        </p>
        <p className="text-xs text-slate-400 mt-2">
          Travel information generated by AI may vary. Always check official sources for visas, closures, and train schedules.
        </p>
      </div>
    </footer>
  );
};